/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public static void main(String[] args) {
        System.out.println("hello");
        Restaurant KFC = new Restaurant("KFC", 4, 7);
        KFC.addReview("good", 2, "Qutadah");
        System.out.println(KFC);
        System.out.println(KFC.addReview("good", 2, "Qutadah"));

Shop shopKFC = new Shop("KFC","Restorant","$$");
        System.out.println(shopKFC);
        KFC.toString();
        System.out.println(shopKFC.addReview("Qutadah","good shop","$"));
    }
}