/*
 * This Java source file was generated by the Gradle 'init' task.
 */


package linter;

import java.io.*;
import java.util.*;
import java.nio.file.*;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        Path file = Paths.get("gates.js");
        readingFromJsFile(file);
    }

    public static String readingFromJsFile(Path file) {
        String errorMessage = "";
        int lineTracer = 1;
        try {
            List<String> fileLines = Files.readAllLines(file);
            for (int i = 0; i < fileLines.size(); i++) {
                if (!fileLines.get(i).endsWith(";") && !(fileLines.get(i).isEmpty()
                        || fileLines.get(i).endsWith("{") || fileLines.get(i).endsWith("}")
                        || fileLines.get(i).contains("if") || fileLines.get(i).contains("else"))){
                    errorMessage = "Line " + lineTracer + " : Missing semicolon.";
                    System.out.println(errorMessage);
                }
                lineTracer++;
            }
        } catch (IOException exception){
            System.out.println("An error occurred while reading from file");
        }
        return errorMessage;
    }
}